version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: website-builder-postgres
    environment:
      POSTGRES_DB: website_builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - website-builder-network

  redis:
    image: redis:7-alpine
    container_name: website-builder-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - website-builder-network

  minio:
    image: minio/minio:latest
    container_name: website-builder-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - website-builder-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  website-builder-network:
    driver: bridge
